#!/bin/bash

llvm_ver=llvm

/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64-unknown-unknown -input=small.o -check-section
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -input=small.o -list
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=host-x86_64-unknown-linux-gnu,sycl-spir64_gen-unknown-unknown -input=small.o -output=./bundle/small-495146.o -output=./bundle/small-debeeb.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/spirv-to-ir-wrapper ./bundle/small-debeeb.o -o ./bundle/small-6a28f5.bc
/opt/$llvm_ver/bin/$llvm_ver-link ./bundle/small-6a28f5.bc -o ./bundle/small-083152.bc --suppress-warnings
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-crt.o -output=./bundle/libsycl-crt-ef2444.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-complex.o -output=./bundle/libsycl-complex-48d991.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-complex-fp64.o -output=./bundle/libsycl-complex-fp64-f6fa4d.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-cmath.o -output=./bundle/libsycl-cmath-6a8827.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-cmath-fp64.o -output=./bundle/libsycl-cmath-fp64-e20135.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-imf.o -output=./bundle/libsycl-imf-424668.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-imf-fp64.o -output=./bundle/libsycl-imf-fp64-aa0749.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-imf-bf16.o -output=./bundle/libsycl-imf-bf16-83f8e3.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-cassert.o -output=./bundle/libsycl-fallback-cassert-54ddcf.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-cstring.o -output=./bundle/libsycl-fallback-cstring-5a15c5.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-complex.o -output=./bundle/libsycl-fallback-complex-a07f6d.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-complex-fp64.o -output=./bundle/libsycl-fallback-complex-fp64-71788b.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-cmath.o -output=./bundle/libsycl-fallback-cmath-11f19d.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-cmath-fp64.o -output=./bundle/libsycl-fallback-cmath-fp64-4e12cd.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-imf.o -output=./bundle/libsycl-fallback-imf-118364.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-imf-fp64.o -output=./bundle/libsycl-fallback-imf-fp64-804ffa.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-fallback-imf-bf16.o -output=./bundle/libsycl-fallback-imf-bf16-c7b3f4.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-native-bfloat16.o -output=./bundle/libsycl-native-bfloat16-f05e1e.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-itt-user-wrappers.o -output=./bundle/libsycl-itt-user-wrappers-b6cc88.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-itt-compiler-wrappers.o -output=./bundle/libsycl-itt-compiler-wrappers-9991cf.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/clang-offload-bundler -type=o -targets=sycl-spir64_gen-unknown-unknown -input=/opt/$llvm_ver/bin/../lib/libsycl-itt-stubs.o -output=./bundle/libsycl-itt-stubs-54093f.o -unbundle -allow-missing-bundles
/opt/$llvm_ver/bin/$llvm_ver-link ./bundle/small-083152.bc ./bundle/libsycl-crt-ef2444.o ./bundle/libsycl-complex-48d991.o ./bundle/libsycl-complex-fp64-f6fa4d.o ./bundle/libsycl-cmath-6a8827.o ./bundle/libsycl-cmath-fp64-e20135.o ./bundle/libsycl-imf-424668.o ./bundle/libsycl-imf-fp64-aa0749.o ./bundle/libsycl-imf-bf16-83f8e3.o ./bundle/libsycl-fallback-cassert-54ddcf.o ./bundle/libsycl-fallback-cstring-5a15c5.o ./bundle/libsycl-fallback-complex-a07f6d.o ./bundle/libsycl-fallback-complex-fp64-71788b.o ./bundle/libsycl-fallback-cmath-11f19d.o ./bundle/libsycl-fallback-cmath-fp64-4e12cd.o ./bundle/libsycl-fallback-imf-118364.o ./bundle/libsycl-fallback-imf-fp64-804ffa.o ./bundle/libsycl-fallback-imf-bf16-c7b3f4.o ./bundle/libsycl-native-bfloat16-f05e1e.o ./bundle/libsycl-itt-user-wrappers-b6cc88.o ./bundle/libsycl-itt-compiler-wrappers-9991cf.o ./bundle/libsycl-itt-stubs-54093f.o -o ./bundle/small-4f6f35.bc --suppress-warnings
/opt/$llvm_ver/bin/sycl-post-link -split=auto -emit-param-info -symbols -emit-exported-symbols -split-esimd -lower-esimd -O3 -spec-const=default -device-globals -o ./bundle/small-326807.table ./bundle/small-4f6f35.bc
/opt/$llvm_ver/bin/file-table-tform -extract=Code -drop_titles -o ./bundle/small-6bd375.txt ./bundle/small-326807.table
/opt/$llvm_ver/bin/$llvm_ver-foreach --in-file-list=./bundle/small-6bd375.txt --in-replace=./bundle/small-6bd375.txt --out-ext=spv --out-file-list=./bundle/small-b0f52b.txt --out-replace=./bundle/small-b0f52b.txt --jobs=1 -- /opt/$llvm_ver/bin/$llvm_ver-spirv -o ./bundle/small-b0f52b.txt -spirv-max-version=1.4 -spirv-debug-info-version=ocl-100 -spirv-allow-extra-diexpressions -spirv-allow-unknown-intrinsics=$llvm_ver.genx. -spirv-ext=-all,+SPV_EXT_shader_atomic_float_add,+SPV_EXT_shader_atomic_float_min_max,+SPV_KHR_no_integer_wrap_decoration,+SPV_KHR_float_controls,+SPV_KHR_expect_assume,+SPV_KHR_linkonce_odr,+SPV_INTEL_subgroups,+SPV_INTEL_media_block_io,+SPV_INTEL_device_side_avc_motion_estimation,+SPV_INTEL_fpga_loop_controls,+SPV_INTEL_unstructured_loop_controls,+SPV_INTEL_fpga_reg,+SPV_INTEL_blocking_pipes,+SPV_INTEL_function_pointers,+SPV_INTEL_kernel_attributes,+SPV_INTEL_io_pipes,+SPV_INTEL_inline_assembly,+SPV_INTEL_arbitrary_precision_integers,+SPV_INTEL_float_controls2,+SPV_INTEL_vector_compute,+SPV_INTEL_fast_composite,+SPV_INTEL_arbitrary_precision_fixed_point,+SPV_INTEL_arbitrary_precision_floating_point,+SPV_INTEL_variable_length_array,+SPV_INTEL_fp_fast_math_mode,+SPV_INTEL_long_constant_composite,+SPV_INTEL_arithmetic_fence,+SPV_INTEL_global_variable_decorations,+SPV_INTEL_token_type,+SPV_INTEL_bfloat16_conversion,+SPV_INTEL_joint_matrix,+SPV_INTEL_hw_thread_queries,+SPV_KHR_uniform_group_instructions,+SPV_INTEL_masked_gather_scatter,+SPV_INTEL_tensor_float32_conversion ./bundle/small-6bd375.txt
/opt/$llvm_ver/bin/$llvm_ver-foreach --out-ext=out --in-file-list=./bundle/small-b0f52b.txt --in-replace=./bundle/small-b0f52b.txt --out-file-list=./bundle/small-470413.out --out-replace=./bundle/small-470413.out --jobs=1 -- /usr/bin/ocloc -output ./bundle/small-470413.out -file ./bundle/small-b0f52b.txt -output_no_suffix -spirv_input -device pvc -internal_options -ze-intel-has-buffer-offset-arg -internal_options -cl-intel-greater-than-4GB-buffer-required
/opt/$llvm_ver/bin/file-table-tform -replace=Code,Code -o ./bundle/small-453a46.table ./bundle/small-326807.table ./bundle/small-470413.out
/opt/$llvm_ver/bin/clang-offload-wrapper -o=./bundle/wrapper-d73baa.bc -host=x86_64-unknown-linux-gnu -target=spir64_gen -kind=sycl -batch ./bundle/small-453a46.table
/opt/$llvm_ver/bin/llc -filetype=obj -o ./bundle/small-wrapper-088608.o ./bundle/wrapper-d73baa.bc
/usr/bin/ld -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o small /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbegin.o /usr/lib/gcc/x86_64-linux-gnu/12/crtfastmath.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/opt/$llvm_ver/bin/../lib -L/lib -L/usr/lib ./bundle/small-495146.o ./bundle/small-wrapper-088608.o -lstdc++ -lm -lgcc_s -lgcc -lsycl -lsycl-devicelib-host -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/12/crtend.o /lib/x86_64-linux-gnu/crtn.o
